### ISSUE TITLE
Package in the AUR

### ISSUE THREAD

**Issue by ghost** [xmonad/xmonad-extras#1]
It will be great to have a package for this in the ArchLinux AUR. This can be a beginner issue for anyone interested :smile:

**Comment by psibi** [comment]
I'm closing this issues as this is not actually a bug related to the package. Please re-open if you disagree.

**Comment by ghost** [comment]
👍

**Comment by LeifW** [comment]
Agreed that this isn't an issue for this repo, but I made a PKGBUILD for this I can push up to AUR shortly.
