### ISSUE TITLE
Is this plugin mergeable?

### ISSUE THREAD

**Issue by giovanifss** [xmonad/xmonad-extras#13]
I have written a [xmonad plugin to update screen brightness in linux](https://github.com/giovanifss/xmonad-brightness). This plugin takes as premise that brigthness can be updated by changing `/sys/class/backlight/intel_backlight/brightness` and the user owning xmonad process has permissions to write there. It serves just for a specific task, but does it fits here in xmonad-extras?

**Comment by psibi** [comment]
Sure, free feel to create a PR. I would like this to have under a new flag which by default is `false`. Also, in the code if you can check whether `/sys/class/backlight/intel_backlight/brightness` exists, it would be good.

**Comment by giovanifss** [comment]
Ok, I've created the pull request (#14).
