### ISSUE TITLE
Out of Stackage for 8.6

### ISSUE THREAD

**Issue by psibi** [xmonad/xmonad-extras#17]
Depends on upstream: https://github.com/xmonad/xmonad-contrib/issues/283

**Comment by peti** [comment]
A new xmonad-contrib version is available from Hackage.

**Comment by psibi** [comment]
Blocked by https://github.com/haskell-hint/hint/issues/75

**Comment by psibi** [comment]
Blocked by libmpd now.

**Comment by psibi** [comment]
It's back in stackage now.
