### ISSUE TITLE
Fail to build against xmonad and xmonad-contrib 0.15

### ISSUE THREAD

**Issue by jokogr** [xmonad/xmonad-extras#18]
Hello,

xmonad and xmonad-contrib 0.15 have both been released and xmonad-extras compilation fails against them:

```
Setup: Encountered missing dependencies:
xmonad >=0.10 && <0.15, xmonad-contrib >=0.10 && <0.15
```

**Comment by psibi** [comment]
It's blocked by the release of hlint: https://github.com/xmonad/xmonad-extras/issues/17#issuecomment-426146739

**Comment by psibi** [comment]
Released a new version to Hackage fixing this.
