### ISSUE TITLE
Xmonad.Util.Brightness missing AMD support.

### ISSUE THREAD

**Issue by qcc-na** [xmonad/xmonad-extras#20]
The documentation on hackage assumes the presence of an intel backlight.
http://hackage.haskell.org/package/xmonad-extras-0.15.1/docs/XMonad-Util-Brightness.html
```
Requirements
    This module assumes that the following files exists:

        /sys/class/backlight/intel_backlight/max_brightness
        /sys/class/backlight/intel_backlight/brightness 
```

I'm on a thinkpad(A485) with an AMD gpu and would greatly appreciate amd support and in fact would be willing take this effort on myself. 

I'm not sure where the `amdgpu_bl0` comes from or if it would even be consistent across amd gpus.

```
$ ls /sys/class/backlight/
amdgpu_bl0
```
What do ya say?

**Comment by psibi** [comment]
@qcc-na Sounds good to me. Can you create an working PR for this ? We can take it from there.

**Comment by psibi** [comment]
Ping @qcc-na

**Comment by qcc-na** [comment]
I moved past this issue by having acpid run a script when I hit the brightness button.

I haven't made any progress on a pr.  You can close if you want.

**Comment by psibi** [comment]
@qcc-na I'm closing the issue now. Free feel to re-open it if you plan to implement this in future. Thanks!
