### ISSUE TITLE
Failed to build xmonad-extras

### ISSUE THREAD

**Issue by davama** [xmonad/xmonad-extras#23]
Hello,

Attempting to build `xmonad-extras` fails
Using the latest github branch from [xmonad](https://github.com/xmonad/xmonad) , [xmonad-contrib](https://github.com/xmonad/xmonad-contrib) and [xmonad-extras](https://github.com/xmonad/xmonad-extras)

```
$ cat ~/.xmonad/stack.yaml | grep -v "^#" | sed '/^$/d'
resolver: lts-14.7
packages:
- xmonad-git/xmonad
- xmonad-git/xmonad-contrib
```
```
xmonad --version
xmonad 0.15
```
```
stack init --force
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- xmonad-git/xmonad-contrib/
- xmonad-git/xmonad-extras/
- xmonad-git/xmonad/

Selecting the best among 16 snapshots...

[...]

Selected resolver: lts-14.7
Resolver 'lts-14.7' does not have all the packages to match your requirements.
    xmonad-contrib version 0.16 found
        - xmonad-extras requires >=0.10 && <0.16
    Using package flags:
        - xmonad-extras: FlagName "testing" = False, FlagName "with_brightness" = True, FlagName "with_hint" = True, FlagName "with_hlist" = False, FlagName "with_mpd" = True, FlagName "with_regex_posix" = True, FlagName "with_sound" = True, FlagName "with_template_haskell" = True

This may be resolved by:
    - Using '--omit-packages' to exclude mismatching package(s).
    - Using '--resolver' to specify a matching snapshot/resolver
```

I've tried with `--resolver lts-14.7` but no change. Am i doing something wrong?

Any input is appreciated.

Thank you,
Dave

**Comment by peti** [comment]
My guess is that `xmonad-extras` needs to relax its version constraints on `xmonad-contrib` to compile with the latest version. Maybe @psibi can help?

**Comment by davama** [comment]
Thank you for the input @peti 
Im assuming it has to do with `xmonad-extras.cabal` file.
Was playing with it a bit but not sure exactly what version numbers to put.
https://github.com/xmonad/xmonad-extras/blob/b4049a84fbd11a119d3c470a5adc78275fa5d009/xmonad-extras.cabal#L45 adjusting to Tried to adjust to: 
`xmonad>=0.15 && <0.16, xmonad-contrib>=0.15 && <0.16`
Similar to [here](https://github.com/xmonad/xmonad-contrib/blob/60101b9a7071575c27ec905ccd02c01887d49200/xmonad-contrib.cabal#L68)

But no change.

**Comment by psibi** [comment]
@davama You would likely need to relax the `xmonad-contrib` changes in the `xmonad-extras` cabal file:

```
xmonad-contrib >= 0.15
```

I will give more time to this tomorrow.

**Comment by davama** [comment]
Thank you @psibi for the reply! 

```
 You would likely need to relax the xmonad-contrib changes in the xmonad-extras cabal file:
```
That works!
Of course not a solution but was able to build!

Should I close issue or leave open?

**Comment by psibi** [comment]
I think we can close this as #24 tracks it now. Thanks!
