### ISSUE TITLE
No list of modules

### ISSUE THREAD

**Issue by jidanni** [xmonad/xmonad-extras#33]
We look at https://github.com/xmonad/xmonad-extras and its README, but we can't find a friendly list of what all the "Various modules for xmonad" are.

**Comment by psibi** [comment]
Does the hackage page help: https://hackage.haskell.org/package/xmonad-extras ?

**Comment by jidanni** [comment]
I see. There are about 10 of them. Well please do your best to make sure people downloading the package have a list that is within the package description and works offline.

**Comment by TheMC47** [comment]
There are two main packages, xmonad and xmonad-contrib, and then also xmonad-extras is a third one to keep the dependencies of xmonad-contrib small. The module lists for all the packages are available on hackage:

- https://hackage.haskell.org/package/xmonad
- https://hackage.haskell.org/package/xmonad-contrib
- https://hackage.haskell.org/package/xmonad-extras

These are *all* xmonad modules. We also provide a module index of all the modules with their descriptions of the current development version (so might be unreleased). You can find it here https://xmonad.github.io/xmonad-docs/

 > Well please do your best to make sure people downloading the package have a list that is within the package description and works offline.

Well, this really depends on how you installed the packages. We can't control how distros package them, but you can always clone the repository you're interested in and build the docs yourself by running `stack haddock`
