### ISSUE TITLE
Add `XMonad.Config.DescriptiveKeys`?

### ISSUE THREAD

**Issue by hoijui** [xmonad/xmonad-extras#34]
It allows to add a human-centered description of a key, which comes in useful e.g. when creating a cheat-sheet.

I am using it, though I am not a Haskell knowledgeable person at all, so it might be superseded by something else...
either way, it makes sense to me, and I wanted to ask what you people think about including it:
<https://hackage.haskell.org/package/DescriptiveKeys>

The source code repo seems to be gone though, and I was unable to find a clone anywhere, which might be a problem. ;-)

**Comment by geekosaur** [comment]
I think most people use https://hackage.haskell.org/package/xmonad-contrib-0.17.1/docs/XMonad-Util-NamedActions.html these days.

**Comment by hoijui** [comment]
Looks like the source code can still be found here:
https://github.com/tonymorris/descriptive-keys

**Comment by hoijui** [comment]
Ah, I just saw: DescriptiveKeys has a descriptive text and a list of tags per key binding, while NamedActions only has the descriptive text.
