### ISSUE TITLE
Release 0.13.0 to hackage

### ISSUE THREAD

**Issue by chris-martin** [xmonad/xmonad-extras#5]
It'd be nice to have the fix for #3 released.

**Comment by psibi** [comment]
Unfortunately 0.13.0 doesn't work yet. The building of `alsa-core` which is a transitive dependency of this package fails with this:

```
Configuring alsa-core-0.5.0.1...
setup-Simple-Cabal-1.22.5.0-x86_64-linux-ghc-7.10.3: The pkg-config package
'alsa' version >=1.0.14 is required but it could not be found.
cabal: Error: some packages failed to install:
alsa-core-0.5.0.1 failed during the configure step. The exception was:
ExitFailure 1
```

I have sent a patch via email to Henning Thielemann fixing the above build error. On the release of new package of `alsa-core`, we can release this. I'm attaching the patch here for reference.
[alsa-core.patch.txt](https://github.com/xmonad/xmonad-extras/files/1098740/alsa-core.patch.txt)

**Comment by psibi** [comment]
xmonad-extras-0.13.0 is released to Hackage: https://hackage.haskell.org/package/xmonad-extras-0.13.0 . Closing the issue.

**Comment by chris-martin** [comment]
Thank you :)
